name: python3
channels:
  - conda-forge
dependencies:
  - python=3.9*
  - pip
  - matplotlib-base=3.3*
  - kwant=1.4*
  - scipy=1.7*
  - holoviews=1.13*
  - feedparser
  - sympy=1.6*
  - pfapack
  - ipython>=6.1.0
  - markdown
  - pip:
    - ruamel.yaml
    - jupyter-book
    - sphinxext.opengraph
    - git+https://gitlab.kwant-project.org/anton-akhmerov/publist.git