name: python3
channels:
  - conda-forge
dependencies:
  - python=3.6
  - matplotlib=2.0.0
  - kwant=1.3* # Untill v1.3 is out
  - scipy=1.1*
  - holoviews=1.7*
  - feedparser=5.2*
  - sympy=1.0*
  - pelican=3.7*
  - ipython>=6.1.0
  - notebook
  - markdown
  - notedown
